
#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Mon Nov 26 17:49:02 CST 2018
#define LUCK_addImageToDocument fcBLhOCfIbjUzyUh
#define LUCK_addToolBar WITlRxaLDswSEWKn
#define LUCK_checkPassword cjNicBtukpPAkffW
#define LUCK_cleanAllData fqDDUJpUIOblyDQn
#define LUCK_deleteAlbumModelWithAbid ZVtEUokrkeeKtfnw
#define LUCK_deletePhotoModelWithPid FkTqROQhtuxgaSjB
#define LUCK_dismissAction zbxDYKLUpNBiaPog
#define LUCK_getCacheImageWithKey cgQoBlnVtJZgCJqs
#define LUCK_getCameraAuthorizationSatusIsAvailable QKoaOflwcSWHCkmy
#define LUCK_getFalsePassword jbOzEVkwDCKJghFr
#define LUCK_getFalsePasswordEnable cNCEXImaKrgZMRdF
#define LUCK_getMainPassword tmzWqBvKvzbEccyl
#define LUCK_getMainPasswordEnable xAuiHbTYyriPPNlZ
#define LUCK_getSecretAlbumModel dWTgJDOGdxtVPqPw
#define LUCK_getUserType ViwvobrdVaWfzFIx
#define LUCK_getZhuaPaiEnable hxsBndyxstmySZAY
#define LUCK_insertAlbumModel ySpuqRQQODeNaRJz
#define LUCK_insertPhotoModel damyyHzbVhpvlJsz
#define LUCK_selectPhotoWithType QIfPCpkFMgZVsSnz
#define LUCK_setFalsePassword PBaERlBGVjlZSGBG
#define LUCK_setFalsePasswordEnabel OWElsnPzhiESPrKN
#define LUCK_setMainPassword ZdHzOkNGGVGSMyDo
#define LUCK_setMainPasswordEnabel rUHNOwsovBVIsGSi
#define LUCK_setUpRootVC hhzccHImwEUumGpA
#define LUCK_setUserType HTrNylWDnkpqYuJz
#define LUCK_setZhuaPaiEnabel vjQpIHmooMIeKjUE
#define LUCK_shareInstance RIIOiKpsIFfSnxPR
#define LUCK_showAddImageSheetView sNrqhxjqagQEepRW
#define LUCK_showPasswordVC osSoiveBCnrqaYpH
#define LUCK_updatePhotoModel DfiIxQarWeMNyhCv
#endif
