
#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Tue Nov 27 09:43:24 CST 2018
#define LUCK_addImageToDocument tCSEOUnsbwqXFQmQ
#define LUCK_addToolBar IatEKJFuoFCCGVvH
#define LUCK_checkPassword eVSeglBiRRjCvUuh
#define LUCK_cleanAllData EAjZWJmeJYxDNEjQ
#define LUCK_deleteAlbumModelWithAbid IRvgbyIuTkDURatO
#define LUCK_deletePhotoModelWithPid vMASqVULhrNXTgsD
#define LUCK_dismissAction wJCgXsvFIedynjbf
#define LUCK_getCacheImageWithKey SsRSvikTZmWOqeDr
#define LUCK_getCameraAuthorizationSatusIsAvailable huwSHOMuFpkGBEqV
#define LUCK_getFalsePassword gsYTbArCaPTxWeZa
#define LUCK_getFalsePasswordEnable QgUrVAEjAiCQcktD
#define LUCK_getMainPassword AaXPGqFZbyjeiMHA
#define LUCK_getMainPasswordEnable TdMJnxrarPjeBpYx
#define LUCK_getSecretAlbumModel BEYgrlkinkbfCiuR
#define LUCK_getUserType drujrbbxAkCuAXPi
#define LUCK_getZhuaPaiEnable tTpPfvlPochnOnPn
#define LUCK_insertAlbumModel PImcRvLydScjjUvm
#define LUCK_insertPhotoModel dslrPnttrOOXYTHj
#define LUCK_selectPhotoWithType mFbalofGfDzRfycs
#define LUCK_setFalsePassword qnSIWMSEECPCyeLT
#define LUCK_setFalsePasswordEnabel sytsMCEAFAtytjWa
#define LUCK_setMainPassword cXwQUlbKlaPtxkAi
#define LUCK_setMainPasswordEnabel lrKveCbDMsUNubJL
#define LUCK_setUpRootVC oGapqyyQXUyMGCuN
#define LUCK_setUserType DwcTmIHKZGLDTfsL
#define LUCK_setZhuaPaiEnabel owFEwbAxfAMvqhGl
#define LUCK_shareInstance rngZxPmCajeRIBkj
#define LUCK_showAddImageSheetView ShsEcdfnjVbJTXDa
#define LUCK_showPasswordVC gbhsADtJuytBtFkR
#define LUCK_updatePhotoModel oTiEmqffvPHGzoMk
#endif
